const baseUrl: string = 'http://10.10.20.126:8088/xmobileadmin/api/v1/';
//  const baseUrl: string = 'http://localhost:8088/xmobileadmin/api/v1/';
//const ealertBaseUrl: string = 'https://t-e-alertsvr.premiumtrustbank.com:8443/api/v1/'; // PTB server
//  const ealertBaseUrl: string = 'http://WIN-OTD5T0PS6E9:8090/api/v1/'; //BLOOM BANK
// const ealertBaseUrl: string = 'http://localhost:8090/api/v1/'; //BLOOM BANK
const ach_UAT_BaseUrl: string = 'http://192.168.207.15:5155/XNETT/api/v2/'
//const ealertBaseUrl: string = 'http://10.18.4.23:8090/api/v1/';
//  const ealertBaseUrl: string = 'http://172.168.0.1:8090/api/v1/';
//  const ealertBaseUrl: string = 'http://10.18.4.53:8090/api/v1/';
//would it keep the local changes.
// const ealertBaseUrl: string = '/api/v1/';
const ealertBaseUrl: string = 'http://10.18.254.91:8090/api/v1/';

export const AppApiUrlsService = {

  // LOGIN             : `${baseUrl}auth/login`,
  FORGOT_PASSWORD: `${baseUrl}auth/passwordReset`,
  DASHBOARD_STATS: `${baseUrl}dashboard/getWidgetStats`,
  DASH_TOTAL_TXN: `${baseUrl}dashboard/getTotalTransactions`,
  DASH_TXN_BY_STA: `${baseUrl}dashboard/getTransactionsByStatus`,
  DASH_TOTAL_SMS: `${baseUrl}dashboard/getTotalSms`,
  // DASH_TOT_CUST     : `${baseUrl}dashboard/getTotalCustomers`,
  DASH_CUST_STA: `${baseUrl}dashboard/getTotalCustomersByStatus`,
  DASH_LOCK_CUST: `${baseUrl}dashboard/getTotalCustomersByLockedStatus`,
  BRANCHES: `${baseUrl}utility/branches`,
  COLLECTIONS: `${baseUrl}utility/collections`,
  CHANNGE_PASS: `${baseUrl}utility/changeAdminPassword`,
  ACTIVITY_LOG: `${baseUrl}utility/getActivityLogs`,
  // CREATE_USER       : `${baseUrl}admin/createAdbUser`,
  GET_USERS: `${baseUrl}admin/getAdbUsers`,
  AUTH_USERS: `${baseUrl}admin/getAdbUsersByAuthStatus`,
  LOCKED_USERS: `${baseUrl}admin/getAdbUsersByLockedStatus`,
  ALL_USERS: `${baseUrl}admin/getAllAdbUsers`,
  UPDATE_USER_STAT: `${baseUrl}admin/updateAdminStatus`,
  // UPDATE_USER       : `${baseUrl}admin/updateAdbUser`,
  AUTHORIZE_USER: `${baseUrl}admin/updateAdminAuthorizeStatus`,
  LOCK_USER: `${baseUrl}admin/updateAdminLockedStatus`,
  RESET_USER_PASS: `${baseUrl}admin/resetAdbUserPassword`,
  GET_COL_USERS: `${baseUrl}admin/collectionUsers`,
  CREATE_COL_USER: `${baseUrl}admin/createCollectionUser`,
  EDIT_COLL_USER: `${baseUrl}admin/editCollectionUser`,
  UPDT_COLL_USER: `${baseUrl}admin/updateCollectionUserStatus`,
  RESET_COLL_USER: `${baseUrl}admin/resetCollectionUserPassword`,
  DEACTIVATED_CUST: `${baseUrl}customer/getDeactivatedCustomers`,
  ACTIVE_CUST: `${baseUrl}customer/getActiveCustomers`,
  AUTH_CUST: `${baseUrl}customer/getCustomersByAuthStatus`,
  LOCK_CUST: `${baseUrl}customer/getLockedCustomers`,
  ALL_CUST: `${baseUrl}customer/getAllCustomers`,
  DEL_CUST: `${baseUrl}customer/deleteCustomer`,
  UPDATE_CUST: `${baseUrl}customer/updateCustomerStatus`,
  // AUTHORIZE_CUST    : `${baseUrl}customer/authorizeCustomer`,
  UNLOCK_CUST: `${baseUrl}customer/unlockCustomer`,
  RESET_PASS: `${baseUrl}customer/resetCustomerPassword`,

  CUST_ACCOUNT: `${baseUrl}customer/saveCustomerAccount`,
  EDIT_CUST: `${baseUrl}customer/updateCustomer`,
  CUST_COMPLAINT: `${baseUrl}customer/getCustomerComplaints`,
  RESOLV_COMPLAINT: `${baseUrl}customer/resolveComplaint`,
  SRCH_CUST_STAT: `${baseUrl}customer/searchCustomerByStatus`,
  SRCH_AUTH_CUST: `${baseUrl}customer/searchAuthCustomerStatus`,
  SRCH_LOCK_CUST: `${baseUrl}customer/searchLockCustomerStatus`,
  SRCH_ALL_CUST: `${baseUrl}customer/searchForAllCustomers`,
  GET_CUST_ACCT: `${baseUrl}customer/getCustomerCIFs`,
  DEL_CUST_ACCT: `${baseUrl}customer/unlinkCustomerAccount`,
  CHQBK_REQ: `${baseUrl}transactions/getChequeBookRequests`,
  UPDT_CHQBK_REQ: `${baseUrl}transactions/updateChequeBookRequest`,
  VERIFY_ACC: `${baseUrl}transactions/verifyAccount`,
  FETCH_ACC: `${baseUrl}transactions/findAccountsByCustId`,
  TRNX_REPORT: `${baseUrl}report/getTransactionsReport`,
  SUBSCBR_REPORT: `${baseUrl}report/getSubscribersReport`,
  EXP_SUBR_REPORT: `${baseUrl}report/exportSubscribersReport`,
  EXP_SUB_BR_REPORT: `${baseUrl}report/exportSubscribersByBranchReport`,
  GIP_REPORT: `${baseUrl}report/getGipReport`,
  GIP_REPORT_DATE: `${baseUrl}report/getGipReportByDate`,
  OTP_REPORT: `${baseUrl}report/getOtpReport`,
  OTP_REPORT_FILTER: `${baseUrl}report/getOtpReportBySearchFilter`,
  SMS_REPORT: `${baseUrl}report/getSmsReport`,
  SMS_REPORT_SRCH: `${baseUrl}report/getSmsReportBySearchFilter`,
  EMAIL_REPORT: `${baseUrl}report/getEmailReport`,
  EMAIL_REPORT_SRH: `${baseUrl}report/getEmailReportBySearchFilter`,
  EXPRESS_REPORT: `${baseUrl}report/getExpressPayTransactions`,
  EXP_EXPR_REPORT: `${baseUrl}report/exportExpressPayTransactions`,


  LOGIN: `${ealertBaseUrl}auth/login`,
  //VALIDATE_TOKEN    : `${ealertBaseUrl}auth/tokenValidate`,
  VALIDATE_TOKEN: `${ach_UAT_BaseUrl}validateTokenEalert`,
  GET_CUSTOMER: `${ealertBaseUrl}customers/findAccount`,
  GET_REG_ACC_DET: `${ealertBaseUrl}accounts/viewAccountDetailsByAccNo`,
  GET_REG_ACC_DET_BY_AC_NUM: `${ealertBaseUrl}viewAccountDetails`,
  GET_REG_EDIT_ACC_DET_BY_AC_NUM: `${ealertBaseUrl}viewAccountDetailsStaging`,
  GET_REG_EDIT_ACC_DET_BY_CUST_NO: `${ealertBaseUrl}viewCustomerDetailsStaging`,

  GET_REG_CUST_DET: `${ealertBaseUrl}customers/viewCustomerDetailsByCustId`,
  GET_UPDATE_CUST: `${ealertBaseUrl}customers/updateCustomer`,
  REG_CUSTOMER: `${ealertBaseUrl}customers/register`,
  CREATE_CUSTOMER: `${ealertBaseUrl}customers/register`,
  UPDATE_CUSTOMER: `${ealertBaseUrl}customers/updateCustomer`,
  UPDATE_ACCOUNT: `${ealertBaseUrl}accounts/updateAccount`,
  REG_CUSTOMER_bulk: `${ealertBaseUrl}customers/bulkRegistration`,
  EXEMPT_CUST_bulk: `${ealertBaseUrl}customers/bulkRegistration`,
  // UN_REG_CUSTOMER   : `${ealertBaseUrl}customers/unregister`,
  REG_CUSTOMER_BULK: `${ealertBaseUrl}customers/register/uploadBulkCustomerFile`,
  CONTACT_BULK_UPLOAD: `${ealertBaseUrl}broadcast/upload/registerBulkBroadcastContacts`,
  DEPARTMENTS: `${ealertBaseUrl}departments`,
  DELETE_DEPARTMENTS: `${ealertBaseUrl}departments`,
  CREATE_DEPARTMENT: `${ealertBaseUrl}departments`,
  GET_ALL_CUST: `${ealertBaseUrl}customers/authorised`,
  GET_ALL_ACCOUNTS: `${ealertBaseUrl}accounts/authorized`,
  GET_EXEMP_CUST: `${ealertBaseUrl}accounts/notReceivingAlerts`,
  GET_CUST_BY_AUTH: `${ealertBaseUrl}customers/getCustomersByAuthStatus`,
  GET_CUST_UN_AUTH: `${ealertBaseUrl}customers/unauthorised`,
  GET_APP_CHARGE: `${ealertBaseUrl}charges/months`,

  GET_BROADCAST_SMS: `${ealertBaseUrl}reports/broadcastSms`,
  GET_STATAEMENT_RECORD: `${ealertBaseUrl}statements/registeredAccounts`,
  GET_CUST_DETAILS_STATE: `${ealertBaseUrl}statements/customers`,
  GENERATE_CUST_STATAEMENT: `${ealertBaseUrl}statements`,

  AUTH_DEL_CUST: `${ealertBaseUrl}customers/deactivated`,
  USER_BRANCHES: `${ealertBaseUrl}admin/branches`,
  USER_ROLES: `${ealertBaseUrl}admin/roles`,
  // USER_DEPARTMENT   : `${ealertBaseUrl}admin/roles`,
  AD_USER_VALIDATION: `${ealertBaseUrl}admin/validateUsername`,
  UN_AUTH_USERS: `${ealertBaseUrl}admin/pendingAuthorization`,
  CREATE_USER: `${ealertBaseUrl}admin/users`,
  DEACTIVATE_USER: `${ealertBaseUrl}admin/users/deactivate`,
  ACTIVATE_USER: `${ealertBaseUrl}admin/users/activate`,
  UPDATE_USER: `${ealertBaseUrl}admin/users`,
  GET_USER_BY_STATUS: `${ealertBaseUrl}admin/users`,
  AUTHORIZE_CUST: `${ealertBaseUrl}customers/authorise`,
  SMS_BRAODCAST: `${ealertBaseUrl}broadcast/smsBroadcastMessage`,
  UN_REG_CUSTOMER: `${ealertBaseUrl}accounts/activateDeactivate`,
  // SMS_BROADCAST     : `${ealertBaseUrl}broadcast/smsBroadcastMessage`,// #omni
  SMS_BROADCAST: `${ealertBaseUrl}broadcast/smsBroadcastMessage`,

  AUTH_BROADCAST: `${ealertBaseUrl}broadcast/smsBroadcastMessage/unauthorised`,
  EMAIL_AUTH_BROADCAST: `${ealertBaseUrl}broadcast/emailBroadcastMessage/unauthorised`,
  AUTH_SMS_BRODT: `${ealertBaseUrl}broadcast/smsBroadcastMessage/authorise`,
  REG_BROD_CONTACT: `${ealertBaseUrl}broadcast/registerBroadcastContact`,
  AUTH_EMAIL_BRODT: `${ealertBaseUrl}broadcast/emailBroadcastMessage`,

  getAccountClass: `${ealertBaseUrl}admin/accountClasses`,
  EMAIL_BROADCAST: `${ealertBaseUrl}broadcast/createEmailBroadcast/upload`,
  GET_CHARGE_AMOUNT: `${ealertBaseUrl}customers/charges`,
  SMS_TRAS_REPORT: `${ealertBaseUrl}reports/transactionSms`,
  BIRTHDAY_SMS_REPORT: `${ealertBaseUrl}reports/birthdaySms`,
  BIRTHDAY_EMAIL_REPORT: `${ealertBaseUrl}reports/birthdayEmail`,
  NEW_ACCOUNT_OPENING_SMS_REPORT: `${ealertBaseUrl}reports/newAccountOpeningSms`,
  NEW_ACCOUNT_OPENING_EMAIL_REPORT: `${ealertBaseUrl}reports/newAccountOpeningEmail`,
  EMAIL_TRAS_REPORT: `${ealertBaseUrl}reports/transactionEmails`,
  DASH_TOT_CUST: `${ealertBaseUrl}dashboard`,
  ACTIVITY_REPORT: `${ealertBaseUrl}reports/activityReport`,
  ALERT_SUMMARY_REPORT: `${ealertBaseUrl}reports/alertSummaryReport`,
  getAllRegCustomer: `${ealertBaseUrl}reports/account`,
  add_Tran_Code_Exemption: `${ealertBaseUrl}admin/addTransactionCodes`,
  remove_Tran_Code_Exemption: `${ealertBaseUrl}admin/removeTransactionCodes`,
  ALL_TRANSACTION_CODES: `${ealertBaseUrl}admin/transactionCodeData`,

  GET_MONTHS: `${ealertBaseUrl}charges/months`,
  GET_YEARS: `${ealertBaseUrl}charges/years`,
  CRG_TRAS_REPORT: `${ealertBaseUrl}reports/charges`,
  PRO_CHRG: `${ealertBaseUrl}charges/processCharge`,
  GET_CHRG_CONFIG: `${ealertBaseUrl}charges/getChargeConfig`,
  CHRG_CONFIG: `${ealertBaseUrl}charges/setChargeConfig`,
  AUTHORIZE_BANK_USER: `${ealertBaseUrl}admin/users/authorize`,
};
