export enum AlertTypesEnum {
    TRANSACTION_SMS = 'TRANSACTION_SMS',
    TRANSACTION_EMAIL = 'TRANSACTION_EMAIL',
    BIRTHDAY_SMS = 'BIRTHDAY_SMS',
    BIRTHDAY_EMAIL = 'BIRTHDAY_EMAIL',
    NEW_ACCOUNT_SMS = 'NEW_ACCOUNT_SMS',
    NEW_ACCOUNT_EMAIL = 'NEW_ACCOUNT_EMAIL'
}

export enum AlertStatusEnum {
    SUCCESS = 'SUCCESS',
    PENDING = 'PENDING',
    FAILED = 'FAILED'
}